build:
  environment:
    distribution: focal
    php:
      version: 7.4
  dependencies:
    before:
      - curl -sS https://getcomposer.org/installer | php -- --2
      - mv composer.phar composer
      - export PATH="$PWD:$PATH"
  tests:
    override:
      - php-scrutinizer-run