build:
  image: default-jammy
  nodes:
    analysis:
      environment:
        php:
          version: 8.1
      dependencies:
        before:
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --2
          - php -v
          - composer --version
      tests:
        override:
          - php-scrutinizer-run