build:
  nodes:
    analysis:
      environment:
        php:
          version: 8.1
      dependencies:
        before:
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=$HOME --filename=composer --2
          - $HOME/composer --version
      tests:
        override:
          - php-scrutinizer-run